# Generated by Django 5.1.6 on 2025-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(max_length=100)),
                ('center_name', models.CharField(max_length=100)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'Appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.TextField(blank=True, max_length=100, null=True)),
                ('blood_type', models.TextField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'Donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('registration_date', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'donors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('submission_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Feedback',
                'managed': False,
            },
        ),
    ]
