# Generated by Django 5.1.3 on 2025-03-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=100, unique=True)),
                ('Age', models.IntegerField()),
                ('National_id', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('phone_contact', models.CharField(max_length=100)),
                ('center', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'USER',
                'managed': True,
            },
        ),
    ]
