# Generated by Django 5.1.3 on 2025-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_user_donor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='National_id',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_contact',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
