# Generated by Django 5.1.3 on 2025-03-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_rename_age_user_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
