# Generated by Django 5.1.3 on 2025-03-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='LOG',
        ),
    ]
