# Generated by Django 5.1.3 on 2025-03-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_rename_login_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='log',
            table='LOG',
        ),
    ]
