# Generated by Django 5.1.3 on 2025-03-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_log_options_alter_log_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LOG',
        ),
    ]
