# Generated by Django 5.1.3 on 2025-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='REQUESTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idNumber', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=100)),
                ('bloodType', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'REQUESTS',
                'managed': True,
            },
        ),
    ]
