# Generated by Django 5.1.3 on 2025-03-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_requests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donors',
            options={'managed': True},
        ),
    ]
