# Generated by Django 5.1.3 on 2025-03-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_alter_donors_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donors',
            old_name='donor_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='donors',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='donors',
            name='registration_date',
        ),
    ]
