# Generated by Django 5.1.6 on 2025-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_rename_donor_id_donors_id_remove_donors_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
