# Generated by Django 5.1.6 on 2025-03-16 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_alter_donors_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
