# Generated by Django 5.1.6 on 2025-03-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_donors_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
